### ISSUE TITLE
Game Crash on Mob Death from Tower

### ISSUE THREAD

**Issue by Finch421** [dianchia/DefenseTower#1]
Put up both the Stone and Fire Towers, both caused a crash to title screen when the Mobs health was reduced to zero. Firing and hits had no issues, just on death. Unsure if it just me and my load order or something else but I figured I'd let you know.

Crash Log: 

Generated on: 2022-07-07 16h53m25s
Game state: Server
Game version: 0.21.23
Game language: en
Steam build: 9036512
Steam name: I_Am_Artyom
Authentication: 76561198032788943
Found 20 loaded mods:
	dianchia.increasedstacksize, v1.0.3 - Increased Stack Size (2827931647)
	maanooak.pawnbox, v1.1 - Pawnbox (2827825378)
	jake.carpenterssalvation, v0.2.2.9 - Carpenters Salvation (2827521528)
	fair.bossfightsummary, v1.0 - Boss Fight Summary (2824816332)
	dianchia.fasterpath, v1.0.1 - Faster Path (2829083798)
	dianchia.vanillapathplus, v1.0 - Vanilla Path Plus (2829993329)
	naii.craftabletraps, v1.0 - Craftable Traps (2828589672)
	james.equipmentexpansion, v1.0 - Equipment Expansion (2829639892)
	churfu.reskinmod, v1.1 - WIP Animal Reskin Mod (2830197396)
	redmoogle.daggers, v1.1 - Daggers Mod (2829481945)
	kodi022.silver, v0.2 - K22-Silver (2829216556)
	de.coloredoutline, v0.1 - Colored Outline (2829581163)
	grim.movement, v1.0 - Movement Evolved (2830633031)
	redmoogle.supertools, v1.1 - Super Tools (2828488602)
	mcwind.colorfulledpanel, v1.0 - Colorful LED Panel Mod (2830750787)
	dianchia.defensetower, v1.0.0 - Defense Tower (2830717128)
	endziogd.asphaltmod, v1.0 - Asphalt Tile (2828716152)
	goliath.portablestorage, v1.01 - Portable Storage (2831152355)
	pt.kewaii.magicalcrops, v1.0.1 - Magical Crops (2831860349)
	trihardest.anotherveinminer, v1.01 - AnotherVeinMiner (2831904077)
Found 20 total mods:
	dianchia.increasedstacksize, v1.0.3 - Increased Stack Size (2827931647)
	maanooak.pawnbox, v1.1 - Pawnbox (2827825378)
	jake.carpenterssalvation, v0.2.2.9 - Carpenters Salvation (2827521528)
	fair.bossfightsummary, v1.0 - Boss Fight Summary (2824816332)
	dianchia.fasterpath, v1.0.1 - Faster Path (2829083798)
	dianchia.vanillapathplus, v1.0 - Vanilla Path Plus (2829993329)
	naii.craftabletraps, v1.0 - Craftable Traps (2828589672)
	james.equipmentexpansion, v1.0 - Equipment Expansion (2829639892)
	churfu.reskinmod, v1.1 - WIP Animal Reskin Mod (2830197396)
	redmoogle.daggers, v1.1 - Daggers Mod (2829481945)
	kodi022.silver, v0.2 - K22-Silver (2829216556)
	de.coloredoutline, v0.1 - Colored Outline (2829581163)
	grim.movement, v1.0 - Movement Evolved (2830633031)
	redmoogle.supertools, v1.1 - Super Tools (2828488602)
	mcwind.colorfulledpanel, v1.0 - Colorful LED Panel Mod (2830750787)
	dianchia.defensetower, v1.0.0 - Defense Tower (2830717128)
	endziogd.asphaltmod, v1.0 - Asphalt Tile (2828716152)
	goliath.portablestorage, v1.01 - Portable Storage (2831152355)
	pt.kewaii.magicalcrops, v1.0.1 - Magical Crops (2831860349)
	trihardest.anotherveinminer, v1.01 - AnotherVeinMiner (2831904077)

Exceptions:
java.lang.NullPointerException
	at necesse.entity.mobs.Mob.onDeath(Mob.java:2134)
	at necesse.entity.mobs.Mob.remove(Mob.java:2048)
	at necesse.entity.mobs.Mob.remove(Mob.java:2033)
	at necesse.entity.mobs.Mob.setHealthHidden(Mob.java:2002)
	at necesse.entity.mobs.Mob.isHit(Mob.java:1393)
	at necesse.entity.mobs.Mob.isServerHit(Mob.java:1454)
	at necesse.entity.projectile.Projectile.hit(Projectile.java:714)
	at necesse.entity.projectile.Projectile.checkCollision(Projectile.java:833)
	at necesse.entity.projectile.Projectile.checkHitCollision(Projectile.java:418)
	at necesse.entity.projectile.Projectile.getDistanceMovedBeforeCollision(Projectile.java:679)
	at necesse.entity.projectile.Projectile.moveDist(Projectile.java:466)
	at necesse.entity.projectile.Projectile.tickMovement(Projectile.java:296)
	at necesse.entity.manager.EntityList.lambda$null$3(EntityList.java:274)
	at necesse.engine.tickManager.PerformanceTimerManager.recordPerformance(PerformanceTimerManager.java:105)
	at necesse.engine.tickManager.Performance.record(Performance.java:10)
	at necesse.entity.manager.EntityList.lambda$frameTick$4(EntityList.java:269)
	at necesse.engine.tickManager.PerformanceTimerManager.recordPerformance(PerformanceTimerManager.java:105)
	at necesse.engine.tickManager.Performance.record(Performance.java:10)
	at necesse.entity.manager.EntityList.frameTick(EntityList.java:268)
	at necesse.entity.manager.EntityManager.frameTick(EntityManager.java:319)
	at necesse.level.maps.Level.frameTick(Level.java:356)
	at necesse.engine.world.LevelManager.frameTick(LevelManager.java:37)
	at necesse.engine.world.World.frameTick(World.java:174)
	at necesse.engine.network.server.Server.frameTick(Server.java:142)
	at necesse.engine.ServerTickThread$1.lambda$null$0(ServerTickThread.java:37)
	at necesse.engine.tickManager.PerformanceTimerManager.recordPerformance(PerformanceTimerManager.java:105)
	at necesse.engine.tickManager.Performance.record(Performance.java:10)
	at necesse.engine.ServerTickThread$1.lambda$update$1(ServerTickThread.java:36)
	at necesse.engine.tickManager.PerformanceTimerManager.recordConstantPerformance(PerformanceTimerManager.java:113)
	at necesse.engine.tickManager.Performance.recordConstant(Performance.java:16)
	at necesse.engine.ServerTickThread$1.update(ServerTickThread.java:33)
	at necesse.engine.tickManager.TickManager.tickLogic(TickManager.java:98)
	at necesse.engine.ServerTickThread.run(ServerTickThread.java:72)

Username: Miller
OS: Microsoft Windows 10 (Home) build 19044
OS arch: amd64
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Memory total: 8.37 GB
Memory used: 7.66 GB
Java path: D:\Steam\steamapps\common\Necesse\jre
Java version: 1.8.0_202
JVM arguments:
	-Xms512m
	-Xmx4G
	-XX:+UnlockExperimentalVMOptions
	-XX:+UseG1GC
	-XX:G1NewSizePercent=20
	-XX:G1ReservePercent=20
	-XX:MaxGCPauseMillis=50
	-XX:G1HeapRegionSize=32M
LWJGL version: 3.3.0 build 21
AppData path: C:\Users\Miller\AppData\Roaming\Necesse\
Working dir: D:\Steam\steamapps\common\Necesse
Natives path: D:\Steam\steamapps\common\Necesse\.\natives
JVM memory max: 4.29 GB
JVM memory used: 622.90 MB / 1.41 GB (44.2%)

Running server: Yes
Server network: LOCAL
Server network in: 100 B/s (15), Total: 9.10 kB (687)
Server network out: 2.12 kB/s (315), Total: 659.69 kB (2807)
Server save name: C:\Users\Miller\AppData\Roaming\Necesse\saves/Settlement Main.zip
Server world time: 1190, day 19
Server game time: 28189589
Server local time: 38556
Server ticks: 771
Players online: 1
	Slot 0: Finch421 at 3760x7936d0
Loaded levels: 1
	3760x7936d0, Size: 300x300, Biome: forest, Entities: 528, Mobs: 63, Projectiles: 2, Pickups: 16

Running client: Yes
Client network: LOCAL
Client network in: 2.12 kB/s (315), Total: 659.69 kB (2807)
Client network out: 100 B/s (15), Total: 9.10 kB (687)
Client world time: 1190, day 19
Client game time: 28189572
Client local time: 38220
Client slot: 0/1
Client level: 3760x7936d0, Size: 300x300, Biome: forest, Entities: 528, Mobs: 63, Projectiles: 2, Pickups: 16

Thanks again for your hard work, keep it up!

**Comment by dianchia** [comment]
Thank you for reporting.
Is this issue reproducible? If it is, can you provide a detail step on how to do so?
On my machine, I can't seem to reproduce this error...

**Comment by Finch421** [comment]
Alright, so went ahead and loaded the mod up with all the mods on my list one at a time and it turns out its a mod conflict with  Magical Crops by Kewaii.  Reproduced it consistently

**Comment by KewaiiGamer** [comment]
> Alright, so went ahead and loaded the mod up with all the mods on my list one at a time and it turns out its a mod conflict with Magical Crops by Kewaii. Reproduced it consistently

Just published a new update for Magical Crops which fixes this issue. Thank you for reporting!

**Comment by dianchia** [comment]
Thanks @Finch421 for reporting the issue. All thanks to @KewaiiGamer for fixing the conflicts.
The issue will be close now.
